(function(g){var window=this;'use strict';var uXa=function(a,b){var c=[];return g.hu(a,{query:b},function(d){c.push(d.getValue());return d.continue()}).then(function(){return c})},w4=function(a,b){return"getAll"in IDBIndex.prototype?g.Wt(a.j.getAll(b,void 0)):uXa(a,b)},vXa=function(a,b){return g.bu(a,["captions"],{mode:"readonly",
Kc:!0},function(c){return g.Kna(c.objectStore("captions"),b,void 0)})},wXa=function(a){var b=new g.Px("und",new g.nA("Default","und",!0));
b.captionTracks=a.captionTracks;return b},xXa=function(a){return new g.Mi(function(b,c){var d=a.length,e=[];
if(d)for(var f=function(n,p){d--;e[n]=p;0==d&&b(e)},k=function(n){c(n)},l=0,m;l<a.length;l++)m=a[l],g.wba(m,g.Wa(f,l),k);
else b(e)})},x4=function(a){this.j=a},y4=function(){x4.apply(this,arguments)},z4=function(){y4.apply(this,arguments)},A4=function(){y4.apply(this,arguments)},B4=function(){y4.apply(this,arguments)},C4=function(){x4.apply(this,arguments)},D4=function(){y4.apply(this,arguments)},E4=function(){y4.apply(this,arguments)},F4=function(){y4.apply(this,arguments)},G4=function(){y4.apply(this,arguments)},H4=function(){y4.apply(this,arguments)},I4=function(){y4.apply(this,arguments)},J4=function(){y4.apply(this,
arguments)},K4=function(){y4.apply(this,arguments)},L4=function(){y4.apply(this,arguments)},M4=function(){y4.apply(this,arguments)},N4=function(){y4.apply(this,arguments)},O4=function(){y4.apply(this,arguments)},P4=function(){y4.apply(this,arguments)},Q4=function(){y4.apply(this,arguments)},R4=function(){y4.apply(this,arguments)},S4=function(){y4.apply(this,arguments)},T4=function(){y4.apply(this,arguments)},U4=function(){y4.apply(this,arguments)},V4=function(){y4.apply(this,arguments)},W4=function(){y4.apply(this,
arguments)},yXa=function(a){var b=g.DD();
b=Object.assign({},b);a=Object.assign({},a);for(var c in b)a[c]?(4!==b[c]&&(b[c]=a[c]),delete a[c]):2!==b[c]&&(b[c]=4);Object.assign(b,a);g.tva(b);JSON.stringify(b);return b},zXa=function(a){var b,c;
return g.A(function(d){if(1==d.j)return g.w(d,g.ru(),2);if(3!=d.j)return(b=d.u)?g.w(d,g.GD(b),3):d.return();c=d.u;return d.return(g.bu(c,["index","media","captions"],{mode:"readwrite",Kc:!0},function(e){var f=IDBKeyRange.bound(a+"|",a+"~");e=[e.objectStore("index").delete(f),e.objectStore("media").delete(f),e.objectStore("captions").delete(f)];return g.Ut.all(e).then(function(){})}))})},AXa=function(){var a,b;
return g.A(function(c){if(1==c.j)return g.w(c,g.ru(),2);if(3!=c.j){a=c.u;if(!a)throw g.St("rvdfd");return g.w(c,g.GD(a),3)}b=c.u;return c.return(g.bu(b,["index","media"],{mode:"readwrite",Kc:!0},function(d){var e={};return g.fu(d.objectStore("index"),{},function(f){var k,l=f.getKey().match(/^([\w\-_]+)\|(a|v)$/),m=g.Ut.resolve(void 0);if(l){var n=l[1];l=l[2];e[n]=e[n]||{};e[n][l]=g.yva(null===(k=f.getValue())||void 0===k?void 0:k.fmts)}else m=f.delete().then(function(){});
return g.Ut.all([f.continue(),m]).then(function(p){return g.q(p).next().value})}).then(function(){for(var f={},k=g.q(Object.keys(e)),l=k.next();!l.done;l=k.next()){l=l.value;
var m=e[l].v;f[l]=e[l].a&&m?1:2}var n=yXa(f);return g.Nna(d.objectStore("media"),{},function(p){var r=p.getKey().match(g.Cva);r&&f[r[1]]||d.objectStore("media").delete(p.getKey());return p.continue()}).then(function(){return n})})}))})},BXa=function(a,b){var c,d;
return g.A(function(e){if(1==e.j)return g.w(e,g.ru(),2);if(3!=e.j){c=e.u;if(!c)throw g.St("wct");return g.w(e,g.GD(c),3)}d=e.u;return g.w(e,g.bu(d,["captions"],{mode:"readwrite",Kc:!0},function(f){var k=[];f=f.objectStore("captions");for(var l=0;l<b.length;l++){var m=g.cu(f,b[l],a+"|"+b[l].metadata.vss_id);k.push(m)}return g.Ut.all(k)}),0)})},CXa=function(a){var b,c,d;
return g.A(function(e){if(1==e.j)return b=IDBKeyRange.bound(a+"|",a+"~"),g.w(e,g.ru(),2);if(3!=e.j){c=e.u;if(!c)throw g.St("gactfv");return g.w(e,g.GD(c),3)}d=e.u;return e.return(vXa(d,b))})},DXa=function(a){return g.A(function(b){g.FD(a,0);
return b.return(zXa(a))})},EXa=function(a){return{context:g.VH(),
videoIds:a}},X4=function(a){a=a.key||a.id;
if(!a)throw Error("Entity key is missing");return a},Y4=function(a,b){b=void 0===b?{}:b;
g.Xs.call(this,g.tTa[a],Object.assign({name:"PESEncoderError",type:a},b));this.type=a;this.level="WARNING";Object.setPrototypeOf(this,Y4.prototype)},FXa=function(a){return new Y4("WRONG_DATA_TYPE",{hU:a})},GXa=function(a){return a instanceof Error?new Y4("UNKNOWN_ENCODE_ERROR",{originalMessage:a.message}):new Y4("UNKNOWN_ENCODE_ERROR")},HXa=function(a){return a instanceof Error?new Y4("UNKNOWN_DECODE_ERROR",{originalMessage:a.message}):new Y4("UNKNOWN_DECODE_ERROR")},IXa=function(a,b){a=a instanceof
Y4?a:b(a);
g.Q(a);throw a;},JXa=function(){},KXa=function(a,b,c){try{return a.B(b,c)}catch(d){IXa(d,GXa)}},LXa=function(a,b,c){try{return a.u(b,c)}catch(d){IXa(d,HXa)}},Z4=function(a){a=(new TextEncoder).encode(a).subarray(0,16);
var b=new Uint8Array(16);b.set(a);return b},$4=function(a){this.j=a},a5=function(){},MXa=function(){this.j={};
this.j[0]=new a5;if(!g.O("aes_pes_encoder_killswitch")){var a=this.j;try{var b=g.Jt();var c=Z4(b);var d=new $4(new g.aC(c),new g.$B(c))}catch(e){throw a=e instanceof Error?new Y4("KEY_CREATION_FAILED",{originalMessage:e.message}):new Y4("KEY_CREATION_FAILED"),g.Q(a),a;}a[1]=d}},b5=function(a,b){b=void 0===b?0:b;
a=a.j[b];if(!a)throw b=new Y4("INVALID_ENCODER_VERSION",{hU:b}),g.Q(b),b;return a},OXa=function(a){var b=NXa[a];
if(b)return b;g.$v(new g.Xs("Entity model not found.",{entityType:a}))},PXa=function(a){var b=new MXa,c=a.objectStore("EntityStore"),d=a.objectStore("EntityAssociationStore");
g.fu(c,{},function(e){var f=e.getValue(),k=LXa(b5(b,f.version),f.data,f.key),l=g.VK(f.key).entityType;l=OXa(l);if(!l)return e.continue();l=(new l(k)).Wd();k=[];l=g.q(l);for(var m=l.next();!m.done;m=l.next())k.push(g.cu(d,{parentEntityKey:f.key,childEntityKey:m.value}));return g.Ut.all(k).then(function(){return e.continue()})})},QXa=function(){if(c5)return c5();
var a={};c5=g.Fu("PersistentEntityStoreDb",{Lq:(a.EntityStore={En:1},a.EntityAssociationStore={En:2},a),ey:!1,upgrade:function(b,c,d){c(1)&&g.eu(g.$t(b,"EntityStore",{keyPath:"key"}),"entityType","entityType");c(2)&&(b=g.$t(b,"EntityAssociationStore",{keyPath:["parentEntityKey","childEntityKey"]}),g.eu(b,"byParentEntityKey","parentEntityKey"),g.eu(b,"byChildEntityKey","childEntityKey"));c(3)&&!c(1)&&PXa(d)},
version:g.O("pes_migrate_association_data")?3:2});return c5()},RXa=function(a){return g.ku(QXa(),a)},SXa=function(a,b){this.j=a;
this.u=b;this.B={}},TXa=function(a,b){return LXa(b5(a.u,b.version),b.data,b.key)},d5=function(a,b,c){return a.j.objectStore("EntityStore").get(b).then(function(d){if(d){if(c&&d.entityType!==c)throw Error("Incorrect entity type");
return TXa(a,d)}})},e5=function(a,b,c){return c?(c=c.map(function(d){return d5(a,d,b)}),g.Ut.all(c)):w4(a.j.objectStore("EntityStore").index("entityType"),IDBKeyRange.only(b)).then(function(d){return d.map(function(e){return TXa(a,e)})})},g5=function(a,b,c){var d=X4(b),e=b5(a.u,1),f={key:d,
entityType:c,data:KXa(e,b,d),version:1};return a.j.objectStore("EntityStore").get(d).then(function(k){if(k&&k.entityType!==c)throw Error("Incorrect entity type");}).then(function(){return g.Ut.all([g.cu(a.j.objectStore("EntityStore"),f),
UXa(a,b,c)])}).then(function(){f5(a,d,c);
return d})},h5=function(a,b,c){b=b.map(function(d){return g5(a,d,c)});
return g.Ut.all(b)},i5=function(a,b,c){if(null===c||void 0===c?0:c.mL){var d=new Set;
return VXa(a,b,d).then(function(){for(var f=[],k=g.q(d),l=k.next();!l.done;l=k.next())f.push(i5(a,l.value));return g.Ut.all(f).then(function(){})})}var e=g.VK(b).entityType;
return g.Ut.all([a.j.objectStore("EntityStore").delete(b),j5(a,b)]).then(function(){f5(a,b,e)})},WXa=function(a,b){return g.hu(a.j.objectStore("EntityStore").index("entityType"),{query:IDBKeyRange.only(b)},function(c){return g.Ut.all([c.delete(),
j5(a,c.oA())]).then(function(){f5(a,c.oA(),b);return c.continue()})})},XXa=function(a,b,c,d){var e=b5(a.u,1);
return d5(a,b,d).then(function(f){if(f){f=g.GK(f,c,void 0);var k={key:b,entityType:d,data:KXa(e,f,b),version:1};return g.Ut.all([g.cu(a.j.objectStore("EntityStore"),k),UXa(a,f,d)])}}).then(function(){f5(a,b,d);
return b})},f5=function(a,b,c){var d=a.B[c];
d||(d=new Set,a.B[c]=d);d.add(b)},YXa=function(a,b,c){var d=X4(b);
c=OXa(c);if(!c)return g.Ut.resolve([]);c=new c(b);a=a.j.objectStore("EntityAssociationStore");b=[];c=g.q(c.Wd());for(var e=c.next();!e.done;e=c.next())b.push(g.cu(a,{parentEntityKey:d,childEntityKey:e.value}));return g.Ut.all(b).then(function(f){return f.map(function(k){return k[1]})})},j5=function(a,b){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b))},UXa=function(a,b,c){var d=X4(b);
return j5(a,d).then(function(){return YXa(a,b,c)})},VXa=function(a,b,c){if(c.has(b))return g.Ut.resolve(void 0);
c.add(b);return ZXa(a,b).then(function(d){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b)).then(function(){return d})}).then(function(d){var e=g.Ut.resolve(void 0),f={};
d=g.q(d);for(var k=d.next();!k.done;f={FC:f.FC},k=d.next())f.FC=k.value,e=e.then(function(l){return function(){return VXa(a,l.FC,c)}}(f));
return e}).then(function(){})},ZXa=function(a,b){var c=a.j.objectStore("EntityAssociationStore");
return w4(c.index("byParentEntityKey"),IDBKeyRange.only(b)).then(function(d){var e=[];d=g.q(d);for(var f=d.next();!f.done;f=d.next())f=f.value,e.push(w4(c.index("byChildEntityKey"),f.childEntityKey));return g.Ut.all(e)}).then(function(d){var e=[];
d=g.q(d);for(var f=d.next();!f.done;f=d.next())f=f.value,1===f.length&&e.push(f[0].childEntityKey);return e})},k5=function(a,b){g.G.call(this);
this.token=a;this.u=b;this.j=[];a=new g.B.BroadcastChannel("PERSISTENT_ENTITY_STORE_SYNC:"+g.Jt());a.onmessage=this.B.bind(this);this.channel=a},l5=function(a,b,c){var d,e,f,k;
return g.A(function(l){if(1==l.j)return g.w(l,RXa(a.token),2);if(3!=l.j)return d=l.u,g.w(l,g.bu(d,["EntityStore","EntityAssociationStore"],b,function(m){e=new SXa(m,a.u);return c(e)}),3);
f=l.u;e&&(k=e.B,0<Object.keys(k).length&&(a.channel.postMessage(k),$Xa(a,k)));return l.return(f)})},m5=function(a,b){a.j.push(b);
return function(){var c=a.j.indexOf(b);0<=c&&a.j.splice(c,1)}},n5=function(a,b,c){return l5(a,{mode:"readwrite",
Kc:!0},function(d){return g5(d,b,c)})},aYa=function(a,b){return l5(a,{mode:"readwrite",
Kc:!0},function(c){return h5(c,b,"offlineOrchestrationActionWrapperEntity")})},bYa=function(a,b){return l5(a,{mode:"readwrite",
Kc:!0},function(c){return i5(c,b,void 0)})},o5=function(a,b,c){return l5(a,{mode:"readonly",
Kc:!0},function(d){return d5(d,b,c)})},p5=function(a,b,c){return l5(a,{mode:"readonly",
Kc:!0},function(d){return e5(d,b,c)})},$Xa=function(a,b){a=g.q(a.j);
for(var c=a.next();!c.done;c=a.next())c=c.value,c(b)},cYa=function(){var a,b,c;
return g.A(function(d){if(1==d.j)return g.ua(d,2),g.w(d,g.ru(),4);if(2!=d.j){a=d.u;if(!a||!g.Kt()||"undefined"===typeof g.B.BroadcastChannel)return d.return();b=new MXa;return d.return(new k5(a,b))}c=g.wa(d);c instanceof Error&&g.Q(c);return d.return()})},r5=function(){q5||(q5=cYa());
return q5},dYa=function(a){var b;
a=null===(b=a.options)||void 0===b?void 0:b.persistenceOption;return"ENTITY_PERSISTENCE_OPTION_PERSIST"===a||"ENTITY_PERSISTENCE_OPTION_INMEMORY_AND_PERSIST"===a},eYa=function(a){var b;
return g.A(function(c){return 1==c.j?g.w(c,r5(),2):(b=c.u)?g.w(c,l5(b,"readwrite",function(d){for(var e={},f={},k=g.q(a),l=k.next();!l.done;f={wg:f.wg,Kr:f.Kr},l=k.next())f.wg=l.value,f.wg.entityKey&&dYa(f.wg)&&(f.Kr=g.Jf(f.wg.payload),l=void 0,"ENTITY_MUTATION_TYPE_REPLACE"===f.wg.type&&(l=function(m){return function(){return g5(d,m.wg.payload[m.Kr],m.Kr)}}(f)),"ENTITY_MUTATION_TYPE_DELETE"===f.wg.type&&(l=function(m){return function(){return i5(d,m.wg.entityKey)}}(f)),"ENTITY_MUTATION_TYPE_UPDATE"===
f.wg.type&&(l=function(m){return function(){return XXa(d,m.wg.entityKey,m.wg.payload[m.Kr],m.Kr)}}(f)),l&&(e[f.wg.entityKey]=e[f.wg.entityKey]?e[f.wg.entityKey].then(l):l()));
return g.Ut.all(Object.values(e))}),0):c.return()})},fYa=function(a){var b;
return g.A(function(c){if(1==c.j){b=a.mutations;if(!b||0>=b.length)return c.return();if(g.I0){var d=b,e={type:"ENTITY_LOADED"};void 0!==d&&(e.payload=d);g.I0.dispatch(e)}return g.w(c,eYa(b),2)}b.length=0;g.ta(c)})},gYa=function(a){return void 0!==a},s5=function(){},t5=function(){},u5=function(a){if(a.includes(":"))throw Error("Invalid user cache name: "+a);
return a+":"+g.Jt("CacheStorage get")},hYa=function(){return g.A(function(a){if(void 0!==v5)return a.return(v5);
v5=new Promise(function(b){var c;return g.A(function(d){switch(d.j){case 1:return g.ua(d,2),g.w(d,w5.open("test-only"),4);case 4:return g.w(d,w5.delete("test-only"),5);case 5:g.va(d,3);break;case 2:if(c=g.wa(d),c instanceof Error&&"SecurityError"===c.name)return b(!1),d.return();case 3:b("caches"in window),g.ta(d)}})});
return a.return(v5)})},y5=function(){return g.A(function(a){if(1==a.j)return g.w(a,hYa(),2);
if(!a.u)return a.return(void 0);x5||(x5=new t5);return a.return(x5)})},iYa=function(){var a;
return g.A(function(b){return 1==b.j?g.w(b,y5(),2):(a=b.u)?b.return(a.delete("yt-player-local-img")):b.return(!0)})},jYa=function(a){var b,c;
return g.A(function(d){if(1==d.j)return g.w(d,y5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.w(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.w(d,Promise.all(a.map(function(e){return c.delete(e)})),0)})},kYa=function(a){var b,c;
return g.A(function(d){if(1==d.j)return g.w(d,y5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.w(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.w(d,c.addAll(a),0)})},z5=function(a,b){var c=b.lj,d,e;
a.encryptedVideoId=b.videoId;a.cotn=c.cotn;a.offlineabilityFormatType=c.maximumDownloadQuality;a.isRefresh=null!==(d=c.isRefresh)&&void 0!==d?d:!1;a.softErrorCount=null!==(e=c.transferRetryCount)&&void 0!==e?e:0;g.Et("offlineTransferStatusChanged",a)},lYa=function(a){z5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_USER_PAUSE",
statusType:"SUSPENDED"},a)},mYa=function(a){switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":return"OFFLINE_DATABASE_ERROR";
case "TRANSFER_FAILURE_REASON_PLAYABILITY":return"NOT_PLAYABLE";case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":return"TOO_MANY_RETRIES";case "TRANSFER_FAILURE_REASON_INTERNAL":return"OFFLINE_DOWNLOAD_CONTROLLER_ERROR";case "TRANSFER_FAILURE_REASON_STREAM_MISSING":return"STREAM_VERIFICATION_FAILED";case "TRANSFER_FAILURE_REASON_SERVER":case "TRANSFER_FAILURE_REASON_SERVER_PROPERTY_MISSING":return"OFFLINE_REQUEST_FAILURE";case "TRANSFER_FAILURE_REASON_NETWORK":return"OFFLINE_NETWORK_ERROR";default:return"UNKNOWN_FAILURE_REASON"}},
A5=function(a){var b,c,d;
return 0<(null!==(d=null===(c=null===(b=a.actionMetadata)||void 0===b?void 0:b.retryScheduleIntervalsInSeconds)||void 0===c?void 0:c.length)&&void 0!==d?d:0)},B5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===a.actionType&&!!a.entityKey},C5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"===a.actionType&&!!a.entityKey},F5=function(a,b,c,d){var e,f,k,l,m,n,p,r,t,u,x,y,z,E,F,H,M,V,K,Z,ma,za,Ia,ub;
return g.A(function(Oa){switch(Oa.j){case 1:return e=g.WK(a,"ytMainVideoEntity"),f=g.WK(a,"ytMainChannelEntity"),k=g.WK(a,"transfer"),g.w(Oa,l5(b,{mode:"readonly",Kc:!0},function(dc){return g.Ut.all([d5(dc,e,"ytMainVideoEntity"),d5(dc,f,"ytMainChannelEntity"),d5(dc,k,"transfer"),e5(dc,"ytMainChannelEntity"),e5(dc,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:l=Oa.u;m=g.q(l);n=m.next().value;p=m.next().value;r=m.next().value;t=m.next().value;u=m.next().value;x=n;y=p;z=r;E=t;F=u;if(!x&&!y){Oa.eb(3);break}H=x?D5(x.thumbnail):[];if(!y){M=[];Oa.eb(4);break}return g.w(Oa,nYa(y,E),5);case 5:M=Oa.u;case 4:return V=M,g.w(Oa,jYa(H.concat(V)),3);case 3:K=[];Z=g.WK(a,"ytMainDownloadedVideoEntity");ma=g.q(F);for(za=ma.next();!za.done;za=ma.next())Ia=za.value,ub=g.VK(Ia.key).entityId,ub!==a||oYa(c,Ia.actionProto)||K.push(Ia.key);return g.w(Oa,l5(b,{mode:"readwrite",
Kc:!0},function(dc){var Yc=K.map(function(wb){return i5(dc,wb)});
Yc.push(i5(dc,Z,{mL:!0}));return g.Ut.all(Yc)}),7);
case 7:pYa(z),E5(d,{entityKey:Z,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.ta(Oa)}})},rYa=function(a,b,c){var d,e,f,k,l,m;
return g.A(function(n){if(1==n.j)return g.w(n,l5(a,{mode:"readwrite",Kc:!0},function(p){var r=e5(p,"transfer"),t=e5(p,"offlineOrchestrationActionWrapperEntity");return g.Ut.all([r,t]).then(function(u){u=g.q(u);var x=u.next().value,y=u.next().value;u=qYa.map(function(H){return WXa(p,H)});
y=g.q(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var E="ytMainDownloadedVideoEntity"===g.VK(z.actionProto.entityKey).entityType,F="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;oYa(b,z.actionProto)||E&&(!E||F)||u.push(i5(p,z.key,{mL:!0}))}return g.Ut.all(u).then(function(){return x})})}),2);
d=n.u;e=g.q(d);for(f=e.next();!f.done;f=e.next())k=f.value,pYa(k),l=g.VK(k.key).entityId,m=g.WK(l,"ytMainDownloadedVideoEntity"),E5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.w(n,iYa(),0)})},oYa=function(a,b){return a.actionType===b.actionType&&a.entityKey===b.entityKey},pYa=function(a){if(a&&"TRANSFER_STATE_COMPLETE"!==a.transferState&&"TRANSFER_STATE_FAILED"!==a.transferState){var b=g.VK(a.key).entityId;
z5({transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_BY_USER",statusType:"CANCELLED"},{videoId:b,lj:a})}},D5=function(a){if(!a||!a.thumbnails)return[];
var b=[];a=g.q(a.thumbnails);for(var c=a.next();!c.done;c=a.next())c=c.value,c.url&&b.push(c.url);return b},nYa=function(a,b){var c,d,e,f,k,l,m,n;
return g.A(function(p){c=D5(a.avatar);d=g.q(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(k=g.q(D5(f.avatar)),l=k.next();!l.done;l=k.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},G5=function(a){this.j=a},sYa=function(a,b){var c,d,e,f,k,l,m;
return g.A(function(n){switch(n.j){case 1:c=new Map,d=g.q(b),e=d.next();case 2:if(e.done){n.eb(4);break}f=e.value;k=c;l=k.set;m=f;return g.w(n,a.B(f),5);case 5:l.call(k,m,n.u);e=d.next();n.eb(2);break;case 4:return n.return(c)}})},H5=function(a,b,c,d){this.status=a;
this.j=b;this.u=c;this.failureReason=d},I5=function(a,b,c){g.$v(new g.Xs("Woffle: "+a,c?{cotn:c}:""));
b instanceof Error&&g.$v(b)},J5=function(a,b,c){this.j=a;
this.Y=b;this.u=c},vYa=function(a,b){var c,d,e,f,k,l,m;
return g.A(function(n){switch(n.j){case 1:e=b.entityKey;f=null===(d=null===(c=b.actionMetadata)||void 0===c?void 0:c.playbackDataActionMetadata)||void 0===d?void 0:d.isEnqueuedForExpiredStreamUrlRefetch;g.ua(n,2);var p;var r=null!==(p=b.actionMetadata)&&void 0!==p&&p.playbackDataActionMetadata?{maximumDownloadQuality:b.actionMetadata.playbackDataActionMetadata.maximumDownloadQuality}:void 0;return g.w(n,tYa(a,e,{isEnqueuedForExpiredStreamUrlRefetch:f,BQ:r}),4);case 4:return(k=n.u)?g.w(n,uYa(a,k,b),
5):n.return(K5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));case 5:return n.return(K5(b,!0,k.orchestrationActions));case 2:return l=g.wa(n),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.Nt&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),I5("PDE handleAdd error"),n.return(K5(b,!1,void 0,m))}})},wYa=function(a,b){var c,d,e,f,k,l,m,n,p,r,t,u,x,y;
return g.A(function(z){switch(z.j){case 1:return c=b.entityKey,g.w(z,l5(a.j,{mode:"readonly",Kc:!0},function(E){var F=d5(E,c,"playbackData"),H=d5(E,g.WK(g.VK(b.entityKey).entityId,"offlineVideoPolicy"),"offlineVideoPolicy");E=d5(E,g.WK(g.VK(b.entityKey).entityId,"transfer"),"transfer");return g.Ut.all([F,H,E])}),2);
case 2:d=z.u;e=g.q(d);f=e.next().value;k=e.next().value;l=e.next().value;m=f;n=k;p=l;if(!m||!n)return z.return(K5(b,!0));r={lastPlayerResponseTimestampSeconds:m.playerResponseTimestamp,offlineToken:n.offlineToken};t={};if(null===p||void 0===p?0:p.maximumDownloadQuality)t.maximumDownloadQuality=p.maximumDownloadQuality;g.ua(z,3);return g.w(z,tYa(a,c,{refreshData:r,BQ:t}),5);case 5:return(u=z.u)?g.w(z,uYa(a,u,b),6):z.return(K5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));
case 6:return z.return(K5(b,!0,u.orchestrationActions));case 3:return x=g.wa(z),y="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",x instanceof g.Nt&&"QUOTA_EXCEEDED"===x.type&&(y="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),z.return(K5(b,!1,void 0,y))}})},tYa=function(a,b,c){var d,e,f;
return g.A(function(k){d=g.rK();var l=a.Y,m=c.refreshData,n=c.isEnqueuedForExpiredStreamUrlRefetch,p=c.BQ,r={entityKey:b};m&&(r.refreshData=m);n&&(r.isExpiredStreamUrlRefetch=n);p&&(r.downloadParameters=p);e={context:g.DK(l),signatureTimestamp:19054,videos:[r]};f=g.VJ(xYa);return k.return(g.aI(d,e,f))})},uYa=function(a,b,c){var d;
return g.A(function(e){if(1==e.j){if(!b.frameworkUpdates||!b.frameworkUpdates.entityBatchUpdate)return e.return();if(!(b.frameworkUpdates.entityBatchUpdate.mutations&&0<b.frameworkUpdates.entityBatchUpdate.mutations.length&&"ENTITY_MUTATION_TYPE_DELETE"===b.frameworkUpdates.entityBatchUpdate.mutations[0].type))return e.eb(2);d=g.VK(b.frameworkUpdates.entityBatchUpdate.mutations[0].entityKey).entityId;return g.w(e,F5(d,a.j,c,a.u),2)}return g.w(e,fYa(b.frameworkUpdates.entityBatchUpdate),0)})},K5=function(a,
b,c,d){return new H5(b?"OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS":"OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",A5(a),c,d)},L5=function(){G5.apply(this,arguments)},zYa=function(a,b){var c,d;
return g.A(function(e){switch(e.j){case 1:return c=A5(b),g.w(e,o5(a.j,b.entityKey,"transfer"),2);case 2:if(d=e.u)return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(e,3);return g.w(e,yYa(a,b),5);case 5:g.va(e,4);break;case 3:return g.wa(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},AYa=function(a,b){var c,
d;
return g.A(function(e){switch(e.j){case 1:return c=A5(b),g.w(e,o5(a.j,b.entityKey,"transfer"),2);case 2:d=e.u;if(!d||"TRANSFER_STATE_COMPLETE"!==d.transferState)return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(e,3);return g.w(e,yYa(a,b,!0),5);case 5:g.va(e,4);break;case 3:return g.wa(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c))}})},yYa=function(a,b,c){c=void 0===c?!1:c;
var d,e,f,k;return g.A(function(l){if(1==l.j)return e=null===(d=b.actionMetadata)||void 0===d?void 0:d.transferEntityActionMetadata,f={key:b.entityKey,transferState:"TRANSFER_STATE_TRANSFER_IN_QUEUE",cotn:g.Jv(16),enqueuedTimestampMs:Date.now().toString(),maximumDownloadQuality:null===e||void 0===e?void 0:e.maximumDownloadQuality,preferredAudioTrack:null===e||void 0===e?void 0:e.preferredAudioTrack,transferRetryCount:0,isRefresh:c},k=g.VK(f.key).entityId,g.w(l,l5(a.j,{mode:"readwrite",Kc:!0},function(m){var n=
[];c&&n.push(i5(m,g.WK(k,"offlineVideoStreams")));n.push(g5(m,f,"transfer"));return g.Ut.all(n)}),2);
z5({transferStatusType:"TRANSFER_STATUS_TYPE_ENQUEUED",statusType:"ADDED_TO_QUEUE"},{videoId:k,lj:f});g.ta(l)})},BYa=function(a,b,c){return new g.aE(a,{cotn:b,
raw_player_response:c,download_media:!0,start:Infinity,disable_watch_next:!0})},CYa=function(){return{priority:1,
retryScheduleIntervalsInSeconds:[1,2,4]}},M5=function(a,b,c,d,e,f,k,l,m,n,p){this.entityType=a;
this.actionId=b;this.action=c;this.parentActionId=d;this.rootActionId=void 0===e?b:e;this.childActionIds=f;this.prereqActionId=k;this.postreqActionIds=l;this.hasChildActionFailed=n;this.retryScheduleIndex=0;this.j=p||Date.now();this.retryScheduleIndex=m||0},N5=function(a){return{key:g.WK(a.actionId,"offlineOrchestrationActionWrapperEntity"),
actionProto:a.action,parentActionId:a.parentActionId,rootActionId:a.rootActionId,childActionIds:a.childActionIds,prereqActionId:a.prereqActionId,postreqActionIds:a.postreqActionIds,retryScheduleIndex:a.retryScheduleIndex,hasChildActionFailed:a.hasChildActionFailed,enqueueTimeSec:(a.j/1E3).toFixed()}},DYa=function(){this.j=new Map},EYa=function(){O5||(O5=new DYa);
return O5},FYa=function(a,b){return{eventType:{flowEventNamespace:"FLOW_EVENT_NAMESPACE_OFFLINE_ORCHESTRATION",
flowEventType:a},metadata:b,statusCode:void 0,csn:void 0}},GYa=function(a,b,c){if(!c){var d=void 0===d?!1:d;
c=a.j.get("FLOW_TYPE_OFFLINE_ORCHESTRATION");if(!c||d)c=g.Jv(16),a.j.set("FLOW_TYPE_OFFLINE_ORCHESTRATION",c)}a={flowNonce:c,flowType:"FLOW_TYPE_OFFLINE_ORCHESTRATION",flowEventType:b.eventType};b.metadata&&(a.flowMetadata=b.metadata);void 0!==b.statusCode&&(a.flowEventStatus=b.statusCode);b.csn&&(a.csn=b.csn);g.Et("flowEvent",a,void 0)},HYa=function(a,b,c){if(!a.action.entityKey)throw Error("entityKey is missing.");
var d=g.VK(a.action.entityKey);a={entityType:d.kU,entityId:d.entityId,offlineOrchestrationActionType:a.action.actionType,orchestrationAction:{orchestrationActionId:a.actionId}};b&&(a.offlineOrchestrationActionResult=b.status,a.isRetryable=b.j);c&&(a.additionalOrchestrationActions=c.map(function(e){return{orchestrationActionId:e.actionId}}));
return a},P5=function(a,b){var c={offlineOrchestrationContext:HYa(a)};
b=FYa(b,c);GYa(EYa(),b,a.rootActionId)},Q5=function(a,b,c){c=void 0===c?[]:c;
b={offlineOrchestrationContext:HYa(a,b,c)};b=FYa(3,b);GYa(EYa(),b,a.rootActionId)},IYa=function(){this.actions=[]},JYa=function(a,b){b=g.q(b);
for(var c=b.next();!c.done;c=b.next())c=c.value,P5(c,1),a.actions.push(c);a.actions.sort(a.j)},KYa=function(a,b){a=g.q(a.actions);
for(var c=a.next();!c.done;c=a.next())if(c.value.actionId===b)return!0;return!1},R5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.ma=b;this.X=c;this.D=d;this.j=new IYa;this.N=new g.Tu;this.C=new g.J(function(){e.retry()});
this.J=NaN;g.I(this,this.C);this.K=m5(this.u,this.Z.bind(this))},MYa=function(a,b,c,d){var e;
return g.A(function(f){if(1==f.j)return e=new R5(a,b,c,d),g.w(f,LYa(e),2);e.B?Promise.resolve():S5(e);return f.return(e)})},S5=function(a){var b,c,d,e,f,k,l,m,n,p,r,t,u,x,y;
return g.A(function(z){switch(z.j){case 1:if(a.B)throw Error("Already processing an action");if(a.isDisposed())return z.return();b=a.j.actions.shift();NYa(a.X,!b);if(void 0===b)return z.return();for(c=[b];;)if((d=a.j.actions[0])&&0===d.retryScheduleIndex&&d.entityType===b.entityType)c.push(a.j.actions.shift());else break;a.B=c;if(e=a.ma[b.entityType]){z.eb(2);break}a.B=void 0;return g.w(z,S5(a),3);case 3:return z.return();case 2:f=g.q(c);for(k=f.next();!k.done;k=f.next())l=k.value,P5(l,2);g.ua(z,
4,5);return g.w(z,sYa(e,c.map(function(E){return E.action})),7);
case 7:m=z.u,n=g.q(c),k=n.next();case 8:if(k.done){z.eb(5);break}p=k.value;r=m.get(p.action);return g.w(z,OYa(a,p,r),9);case 9:k=n.next();z.eb(8);break;case 5:g.xa(z);a.B=void 0;g.ya(z,6);break;case 4:return t=g.wa(z),I5("Orchestration error",t),g.ua(z,12),g.w(z,PYa(a,c),14);case 14:g.va(z,5);break;case 12:u=g.wa(z);I5("Orchestration retry error",u);x=g.q(c);for(k=x.next();!k.done;k=x.next())y=k.value,3>y.retryScheduleIndex&&JYa(a.j,[y]);z.eb(5);break;case 6:return g.w(z,S5(a),0)}})},OYa=function(a,
b,c){var d,e,f,k,l;
return g.A(function(m){if(1==m.j){if("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS"===c.status){k=void 0;try{k=null===(d=c.u)||void 0===d?void 0:d.map(function(n){return a.createAction(n,b)})}catch(n){return Q5(b,c),l={entityKey:b.action.entityKey,
failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNSUPPORTED_ENTITY_FAILED"},E5(a.D,l),I5("Orchestration subactions creation error",n),m.return()}Q5(b,c,k);return g.w(m,l5(a.u,{mode:"readwrite",Kc:!0},function(n){var p=[];if(k){var r=k.map(function(t){return N5(t)});
p.push(h5(n,r,"offlineOrchestrationActionWrapperEntity"))}r=N5(b);p.push(i5(n,r.key));return g.Ut.all(p)}),9)}if("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE"!==c.status)return m.eb(0);
Q5(b,c);if(c.j&&3>b.retryScheduleIndex+1)return g.w(m,PYa(a,[b]),0);e=(null===c||void 0===c?0:c.failureReason)?c.failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN";f={entityKey:b.action.entityKey,failureReason:e};E5(a.D,f);I5("Orchestration result is not retryable, deleting action");return g.w(m,bYa(a.u,N5(b).key),0)}P5(b,4);g.ta(m)})},T5=function(a,b){var c,d,e,f,k,l,m,n,p,r,t,u;
return g.A(function(x){c=[];d=Infinity;e=4E3;f=g.q(b);for(k=f.next();!k.done;k=f.next())l=k.value,m=Number(l.enqueueTimeSec),n=QYa(m),p=l.retryScheduleIndex,r=null!=p&&0<p,0<n&&r?(d=Math.min(d,m),e=Math.min(n,e)):c.push(l);isFinite(d)&&(!a.C.isActive()||d<a.J)&&(a.J=d,a.C.start(e));a.N.Ne()||(t=c.length,c=c.filter(function(y){var z;y=(null===(z=y.actionProto)||void 0===z?void 0:z.actionType)||"OFFLINE_ORCHESTRATION_ACTION_TYPE_UNKNOWN";return!RYa.includes(y)}),u=c.length<t,!a.C.isActive()&&u&&a.C.start(1));
0<c.length&&SYa(a,c);return g.w(x,a.B?Promise.resolve():S5(a),0)})},UYa=function(a){var b,c,d,e,f,k,l;
return g.A(function(m){if(1==m.j)return g.w(m,TYa(a),2);b=m.u;c=[];d=g.q(b);for(e=d.next();!e.done;e=d.next())f=e.value,k=g.VK(f.key),l=k.entityId,KYa(a.j,l)||c.push(f);return g.w(m,T5(a,c),0)})},QYa=function(a){a=1E3*a-Date.now();
return 4E3<a?4E3:a},PYa=function(a,b){var c,d,e;
return g.A(function(f){c=g.q(b);for(d=c.next();!d.done;d=c.next()){e=d.value;var k=void 0,l=void 0,m=(null===(k=null===(l=e.action)||void 0===l?void 0:l.actionMetadata)||void 0===k?void 0:k.retryScheduleIntervalsInSeconds)||[1,2,4];k=1;e.retryScheduleIndex<m.length&&(k=m[e.retryScheduleIndex]);e.j=1E3*k+Date.now();e.retryScheduleIndex++}return g.w(f,VYa(a,b),0)})},LYa=function(a){var b;
return g.A(function(c){if(1==c.j)return g.w(c,p5(a.u,"offlineOrchestrationActionWrapperEntity"),2);b=c.u;return g.w(c,T5(a,b),0)})},SYa=function(a,b){0!==b.length&&b.forEach(function(c){if(!c.key)throw Error("Entity key is required.");
if(!c.actionProto)throw Error("OfflineOrchestrationAction is required.");var d=g.VK(c.key),e=g.VK(c.actionProto.entityKey);c=new M5(e.entityType,d.entityId,c.actionProto,c.parentActionId,c.rootActionId,c.childActionIds,c.prereqActionId,c.postreqActionIds,c.retryScheduleIndex,c.hasChildActionFailed,1E3*Number(c.enqueueTimeSec));3>c.retryScheduleIndex&&JYa(a.j,[c])})},TYa=function(a,b){var c;
return g.A(function(d){if(1==d.j)return g.w(d,p5(a.u,"offlineOrchestrationActionWrapperEntity",b),2);c=d.u;return d.return(c.filter(gYa))})},VYa=function(a,b){if(0===b.length)return Promise.resolve([]);
b=b.map(function(c){return N5(c)});
return aYa(a.u,b)},WYa=function(a){var b,c,d,e,f,k,l,m,n,p,r,t,u,x,y,z,E;
return g.A(function(F){if(1==F.j)return g.w(F,l5(a,{mode:"readonly",Kc:!0},function(H){return e5(H,"playbackData").then(function(M){var V=M.map(function(Z){return Z.transfer}).filter(function(Z){return!!Z}),K=M.map(function(Z){return Z.offlineVideoPolicy}).filter(function(Z){return!!Z});
V=e5(H,"transfer",V);K=e5(H,"offlineVideoPolicy",K);return g.Ut.all([V,K]).then(function(Z){var ma=g.q(Z);Z=ma.next().value;ma=ma.next().value;return[M,Z,ma]})})}),2);
b=F.u;c=g.q(b);d=c.next().value;e=c.next().value;f=c.next().value;k=d;l=e;m=f;n={};p={};r=g.q(l);for(t=r.next();!t.done;t=r.next())(u=t.value)&&(n[u.key]=u);x=g.q(m);for(y=x.next();!y.done;y=x.next())(z=y.value)&&(p[z.key]=z);E=k.map(function(H){var M=n[H.transfer],V=p[H.offlineVideoPolicy];H=g.VK(V.key).entityId;if("OFFLINE_VIDEO_POLICY_ACTION_DISABLE"===V.action){var K="OFFLINE_VIDEO_STATE_DISABLED";V.expirationTimestamp&&Number(V.expirationTimestamp)<Date.now()/1E3&&(K="OFFLINE_VIDEO_STATE_EXPIRED");
V=K}else if("OFFLINE_VIDEO_POLICY_ACTION_DOWNLOAD_FAILED"===V.action)V="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";else{switch(null===M||void 0===M?void 0:M.transferState){case "TRANSFER_STATE_TRANSFER_IN_QUEUE":K="OFFLINE_VIDEO_STATE_PENDING";break;case "TRANSFER_STATE_TRANSFERRING":K="OFFLINE_VIDEO_STATE_TRANSFERRING";break;case "TRANSFER_STATE_PAUSED_BY_USER":K="OFFLINE_VIDEO_STATE_PAUSED_TRANSFER";break;case "TRANSFER_STATE_FAILED":K="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";break;case "TRANSFER_STATE_COMPLETE":K=
"OFFLINE_VIDEO_STATE_PLAYABLE";break;case "TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH":K="OFFLINE_VIDEO_STATE_STREAMS_OUT_OF_DATE";break;default:K="OFFLINE_VIDEO_STATE_UNKNOWN"}if("OFFLINE_VIDEO_STATE_OFFLINE_FAILED"===K)switch(null===M||void 0===M?void 0:M.failureReason){case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":K="OFFLINE_VIDEO_STATE_OUT_OF_STORAGE_ERROR";break;case "TRANSFER_FAILURE_REASON_STREAM_MISSING":K="OFFLINE_VIDEO_STATE_STREAMS_MISSING";
break;case "TRANSFER_FAILURE_REASON_NETWORK":case "TRANSFER_FAILURE_REASON_NETWORK_LOST":K="OFFLINE_VIDEO_STATE_NETWORK_ERROR"}V=K}H={id:H,videoState:V};if(null===M||void 0===M?0:M.cotn)H.cotn=M.cotn;if(null===M||void 0===M?0:M.maximumDownloadQuality)H.selectedVideoQuality=null===M||void 0===M?void 0:M.maximumDownloadQuality;return H});
return F.return({offlineVideos:E})})},XYa=function(a){var b;
return g.A(function(c){if(1==c.j)return g.w(c,WYa(a),2);b=c.u;g.Et("offlineStateSnapshot",b);g.ta(c)})},U5=function(a){g.G.call(this);
this.api=a;"undefined"!==typeof g.B.BroadcastChannel&&(this.j=new g.B.BroadcastChannel("PLAYER_OFFLINE_ERROR_SYNC:"+g.Jt()),this.j.onmessage=this.B.bind(this),this.u=new g.B.BroadcastChannel("PLAYER_OFFLINE_PAUSE_SYNC:"+g.Jt()),this.u.onmessage=this.C.bind(this))},E5=function(a,b){var c;
a.api.Qa("onOfflineOperationFailure",b);null===(c=a.j)||void 0===c?void 0:c.postMessage(b)},YYa=function(){this.locks=navigator.locks},ZYa=function(){try{var a=g.Ka("ytglobal.locks_");
if(a)return a;var b;if(b=navigator){var c=navigator;b="locks"in c&&!!c.locks}if(b)return g.B.localStorage&&g.B.localStorage.getItem("noop"),a=new YYa,g.Ja("ytglobal.locks_",a,void 0),a}catch(d){}},aZa=function(a,b,c,d){var e=this;
this.N=a;this.X=b;this.visibility=c;this.S=d;this.C=this.J=this.D=this.u=this.j=!1;this.K=new g.J(function(){$Ya(e)});
this.visibility.subscribe("visibilitystatechange",function(){e.Oe()})},bZa=function(a){if(!a.u&&!a.j){var b=ZYa();
if(b){a.u=!0;var c=g.Jt("OfflineLockManager");b.request("woffle_orchestration_leader:"+c,{},function(){var d,e,f;return g.A(function(k){switch(k.j){case 1:return g.ua(k,2),a.B=new g.ek,a.j=!0,a.u=!1,g.w(k,a.N(),4);case 4:return g.w(k,a.B.promise,5);case 5:g.va(k,0);break;case 2:e=g.wa(k),(null===(d=a.S)||void 0===d?0:d.call(a,"wo_relinquish_leadership_on_lock_request_error"))||$Ya(a),e instanceof Error&&(f=e,f.args=[{name:"WoLockManagerError",vB:e.name}],g.Q(f)),g.ta(k)}})})}}},cZa=function(a){a.j&&
(a.C=!0,V5(a))},NYa=function(a,b){a.j&&(a.D=b,V5(a))},dZa=function(a,b){a.j&&(a.J=b,V5(a))},V5=function(a){a.J&&a.D&&a.C&&a.visibility.isBackground()?g.Bp(a.K,6E4):a.K.stop()},$Ya=function(a){a.B&&a.B.resolve();
a.j=!1;a.u=!1;a.X()},eZa=function(){this.j=void 0},gZa=function(a,b){var c,d,e,f,k;
return g.A(function(l){c=b.videoId;d=b.U();e=!0;if(b.captionTracks.length)f=wXa(b),a.j=new g.FL(d,b,f);else if(b.Lb)k=g.Owa(b),a.j=new g.HL(d,b.Lb,c,k,b.vj),e=b.vj;else return l.return();return l.return(new Promise(function(m){var n;null===(n=a.j)||void 0===n?void 0:n.Ot(function(){return g.A(function(p){if(1==p.j)return g.w(p,fZa(a,c,e),2);m();g.ta(p)})})}))})},fZa=function(a,b,c){c=void 0===c?!0:c;
var d,e,f,k,l,m,n,p,r,t,u,x,y,z;return g.A(function(E){switch(E.j){case 1:if(!a.j)return E.return();d=[];e=g.CL(a.j.u,c);f=[];k={};l=g.q(e.entries());for(m=l.next();!m.done;k={BC:k.BC},m=l.next())n=m.value,p=g.q(n),r=p.next().value,t=p.next().value,k.BC=r,u=t,x=a.j.oq(u,"json3"),y=g.Rr(x,{withCredentials:!0},3,500).then(function(F){return function(H){H={metadata:g.LD(e[F.BC]),trackData:H.xhr.responseText};f.push(H)}}(k)).Dh(function(F){I5("Caption fetch error",F)}),d.push(y);
return g.w(E,xXa(d),2);case 2:return g.ua(E,3),g.w(E,BXa(b,f),5);case 5:g.va(E,0);break;case 3:z=g.wa(E),I5("Caption DB transaction error",z),g.ta(E)}})},hZa=function(a){var b;
return g.A(function(c){if(1==c.j)return g.w(c,CXa(a),2);b=c.u;return c.return(!!b&&0<b.length)})},iZa=function(a,b){this.api=a;
this.j=b;this.logger=new g.yQ("woffle");this.u=!1;g.BD=this.api.U().S("html5_user_partitioned_ls")},jZa=function(a){return g.A(function(b){return b.return(DXa(a))})},kZa=function(a){var b;
return g.A(function(c){if(1==c.j)return g.w(c,g.zva(a),2);b=c.u;return c.return(b.filter(function(d){return!!d.url}).map(function(d){return d.url}))})},W5=function(a,b){var c=g.ED(b);
if(1===c||0===c)return Promise.resolve();(c=lZa(a,b))&&c.stopVideo();a.B=0;return jZa(b)},X5=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?!0:d;var e="string"===typeof b?b:b.videoDetails.videoId;2===g.ED(e)&&((b=lZa(a,e))?b.stopVideo():a.logger.info(function(){return"Corresponding player for "+e+" not found. Pausing anyway"}),g.FD(e,2),a.B=2,c?mZa(a.j):d&&nZa(a.j))},lZa=function(a,b){var c;
return(null===(c=a.player)||void 0===c?void 0:c.getVideoData().videoId)===b?a.player:null},oZa=function(a){switch(a){case "HD_1080":return"hd1080";
case "HD":return"hd720";case "SD":return"large";case "LD":return"tiny";default:return"hd720"}},Y5=function(a){g.G.call(this);
this.j=a;this.u=m5(this.j,this.B.bind(this))},pZa=function(a,b){var c,d,e,f,k,l,m;
return g.A(function(n){switch(n.j){case 1:if(0===b.length)return n.return([]);c=b.map(function(p){return g.WK(p,"transfer")});
return g.w(n,p5(a.j,"transfer",c),2);case 2:d=n.u;e=d.filter(gYa).map(function(p){return g.VK(p.key).entityId});
f=b.filter(function(p){return-1===e.indexOf(p)});
if(0===f.length)return n.return([]);k=g.q(f);l=k.next();case 3:if(l.done){n.eb(5);break}m=l.value;return g.w(n,jZa(m),4);case 4:l=k.next();n.eb(3);break;case 5:return n.return(f)}})},rZa=function(a,b,c,d,e,f){var k,l,m;
return g.A(function(n){k="STREAM_TYPE_UNKNOWN";c.video&&c.audio?(k="STREAM_TYPE_AUDIO_AND_VIDEO",I5("unexpected stream type")):c.video&&!c.audio?k="STREAM_TYPE_VIDEO":!c.video&&c.audio&&(k="STREAM_TYPE_AUDIO");l=g.WK(b,"offlineVideoStreams");m={numBytesDownloaded:e.toFixed(),numTotalBytes:f.toFixed(),streamType:k,streamState:"DOWNLOAD_STREAM_STATE_IN_PROGRESS",formatStreamBytes:JSON.stringify(d),itag:"STREAM_TYPE_AUDIO_AND_VIDEO"===k?Number(c.Yb()):void 0};return g.w(n,l5(a,{mode:"readwrite",Kc:!0},
function(p){var r=d5(p,l,"offlineVideoStreams"),t=d5(p,g.WK(b,"transfer"),"transfer");return g.Ut.all([r,t]).then(function(u){var x=g.q(u);u=x.next().value;x=x.next().value;if(!x)return i5(p,l).then(function(){});
u=[g5(p,qZa(u,d,m,l),"offlineVideoStreams")];x.offlineVideoStreams||(x.offlineVideoStreams=[]);-1===x.offlineVideoStreams.indexOf(l)&&(x.offlineVideoStreams.push(l),u.push(g5(p,x,"transfer")));return g.Ut.all(u)})}),0)})},sZa=function(a,b){var c,d,e,f,k;
return g.A(function(l){if(1==l.j)return c=g.WK(b,"offlineVideoStreams"),g.w(l,o5(a,c,"offlineVideoStreams"),2);d=l.u;if(!d||!d.streamsProgress)return l.return();e=g.q(d.streamsProgress);for(f=e.next();!f.done;f=e.next())k=f.value,k.streamState="DOWNLOAD_STREAM_STATE_COMPLETE",k.numTotalBytes!==k.numBytesDownloaded&&(k.numBytesDownloaded=k.numTotalBytes);return g.w(l,n5(a,d,"offlineVideoStreams"),0)})},qZa=function(a,b,c,d){if(a&&a.streamsProgress){d=a;
a:{b=b.itag+";"+b.xtags;for(var e=a.streamsProgress,f=0;f<e.length;f++){var k=JSON.parse(e[f].formatStreamBytes);if(k.itag+";"+k.xtags===b){e[f]=c;c=e;break a}}e.push(c);c=e}d.streamsProgress=c}else a={key:d,streamsProgress:[c]};return a},Z5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.api=b;this.ya=c;this.xa=d;this.D=new g.Tu;this.C=new g.J(function(){e.j&&"TRANSFER_STATE_TRANSFERRING"===e.j.transferState&&e.D.Ne()&&(3>(e.j.transferRetryCount||0)?X5(e.J,e.B,!1,!1):W5(e.J,e.B.videoDetails.videoId),e.Oq("TRANSFER_FAILURE_REASON_TIMEOUT_NO_PROGRESS"))});
this.X=0;this.va=new g.oA(this);this.K=m5(this.u,this.AS.bind(this));this.J=new iZa(b,this);this.Ia=new eZa;this.N=new Y5(this.u);this.ma=this.D.Pa("publicytnetworkstatus-online",this.Ux.bind(this));this.Z=this.D.Pa("publicytnetworkstatus-offline",this.fZ.bind(this));g.I(this,this.va);this.va.T(b,"offlinetransferpause",this.gZ);this.Ea=g.xB(this.api.U().experiments,"web_player_transfer_timeout_threshold_ms")},tZa=function(a){g.A(function(b){if(1==b.j)b=g.w(b,AXa(),2);
else{var c=a.N;var d=g.DD();d=Object.keys(d);c=pZa(c,d);b=g.w(b,c,0)}return b})},a6=function(a,b){b=void 0===b?!1:b;
var c;return g.A(function(d){if(1==d.j){if(a.j)throw Error("Already downloading a video");return g.w(d,uZa(a),2)}return 4!=d.j?(c=d.u,dZa(a.ya,!c),c&&a.D.Ne()?b?g.w(d,new Promise(function(e){g.Ir(e,1E3)}),4):d.eb(4):(!c&&a.j&&$5(a),d.eb(0))):g.w(d,vZa(a,c),0)})},wZa=function(a){return g.A(function(b){if(1==b.j)return a.B?g.w(b,W5(a.J,a.B.videoDetails.videoId),3):b.eb(0);
$5(a);g.ta(b)})},xZa=function(a,b){var c,d,e;
return g.A(function(f){switch(f.j){case 1:return g.ua(f,2),(c=!!b.captionTracks.length||!!b.Lb)?g.w(f,hZa(b.videoId),4):f.return();case 4:return(d=f.u)?f.return():g.w(f,gZa(a.Ia,b),5);case 5:g.va(f,0);break;case 2:e=g.wa(f),I5("Caption downloading error",e,b.cotn),g.ta(f)}})},vZa=function(a,b){var c,d,e,f,k;
return g.A(function(l){switch(l.j){case 1:return a.j=b,"TRANSFER_STATE_TRANSFERRING"===a.j.transferState&&(c=g.VK(a.j.key),z5({transferStatusType:"TRANSFER_STATUS_TYPE_RESUME_PROCESSING",statusType:"OFFLINING_RETRIED"},{videoId:c.entityId,lj:a.j})),g.w(l,b6(a),2);case 2:return d=null,g.ua(l,3),g.w(l,yZa(a,b),5);case 5:d=l.u;a.B=d;g.va(l,4);break;case 3:return e=g.wa(l),I5("error getting player response",e,b.cotn),g.w(l,a.Oq("TRANSFER_FAILURE_REASON_INTERNAL"),6);case 6:return l.return();case 4:return f=
BYa(a.api.U(),b.cotn,d),g.w(l,xZa(a,f),7);case 7:return k=f,g.w(l,kZa(f.videoId),8);case 8:k.Rl=l.u;var m=a.J,n=b.maximumDownloadQuality,p;f.getPlayerResponse();g.FD(f.videoId,2);m.B=2;m.u=!1;null===(p=m.player)||void 0===p?void 0:p.dispose();m.player=m.api.Ln(9,f);p={};g.rv(m.player,(p.localmediachange=m.lB,p.signatureexpired=m.OG,p.statechange=m.VW,p),m);n=oZa(n);m.S("hoffle_lmqf_killswitch")||(n=g.Sx(n,n,!0,"m"),g.bMa(m.player,n,!1));g.PP(m.player,!1);c6(a);g.ta(l)}})},uZa=function(a){var b,c;
return g.A(function(d){if(1==d.j)return g.w(d,p5(a.u,"transfer"),2);b=d.u;c=b.filter(zZa).sort(AZa);return 0===c.length?d.return():d.return(c[0])})},b6=function(a){return g.A(function(b){c6(a);
return g.w(b,d6(a,"TRANSFER_STATE_TRANSFERRING"),0)})},mZa=function(a){var b;
g.A(function(c){if(1==c.j)return a.C.stop(),g.w(c,d6(a,"TRANSFER_STATE_PAUSED_BY_USER"),2);b=g.VK(a.j.key);lYa({videoId:b.entityId,lj:a.j});$5(a);a6(a);g.ta(c)})},nZa=function(a){g.A(function(b){if(1==b.j)return a.C.stop(),g.w(b,d6(a,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),2);
$5(a);g.ta(b)})},BZa=function(a){var b,c,d;
g.A(function(e){switch(e.j){case 1:a.C.stop();if(!a.j||!a.B){e.eb(2);break}b=BYa(a.api.U(),a.j.cotn,a.B);return g.w(e,xZa(a,b),2);case 2:return g.w(e,d6(a,"TRANSFER_STATE_COMPLETE","DOWNLOAD_STREAM_STATE_COMPLETE"),4);case 4:return c=g.VK(a.j.key),d=c.entityId,g.w(e,sZa(a.u,d),5);case 5:z5({transferStatusType:"TRANSFER_STATUS_TYPE_COMPLETED",statusType:"SUCCESS"},{videoId:d,lj:a.j}),$5(a),a6(a),g.ta(e)}})},CZa=function(a,b,c){var d;
g.A(function(e){switch(e.j){case 1:if("TRANSFER_STATE_TRANSFERRING"===a.j.transferState){e.eb(2);break}return g.w(e,b6(a),2);case 2:d=Date.now();if(!(1E3<d-a.X)){e.eb(4);break}a.X=d;return g.w(e,rZa(a.u,c.videoId,c.u,c.formatStream,c.bytesDownloaded,c.j),5);case 5:var f=Math.floor(c.bytesDownloaded/1024).toFixed();z5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",alreadyDownloadedKbytes:f,totalFetchedKbytes:f,totalContentKbytes:Math.floor(c.j/1024).toFixed()},
{videoId:b,lj:a.j});case 4:c6(a),g.ta(e)}})},DZa=function(a){var b=3>(a.j.transferRetryCount||0);
b&&(a=a.j,a.transferRetryCount=(a.transferRetryCount||0)+1);return b},EZa=function(a,b){b=void 0===b?"TRANSFER_FAILURE_REASON_UNKNOWN":b;
var c,d;return g.A(function(e){if(1==e.j)return c="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN","TRANSFER_FAILURE_REASON_NETWORK"===b?c="OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED":"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"===b&&(c="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),g.w(e,d6(a,"TRANSFER_STATE_FAILED","DOWNLOAD_STREAM_STATE_ERROR_STREAMS_MISSING",b),2);E5(a.xa,{entityKey:a.j.key,failureReason:c});d=g.VK(a.j.key).entityId;var f={videoId:d,lj:a.j},k=b,l={transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_WITH_FAILURE",
statusType:"FAILED"};k&&(l.transferFailureReason=k,l.failureReason=mYa(k));z5(l,f);g.ta(e)})},d6=function(a,b,c,d){var e;
return g.A(function(f){if(1==f.j)return a.j.transferState=b,a.j.failureReason=d,g.ua(f,2),g.w(f,FZa(a,function(k){return c?e5(k,"offlineVideoStreams",a.j.offlineVideoStreams).then(function(l){for(var m=g.q(l),n=m.next();!n.done;n=m.next())if((n=n.value)&&n.streamsProgress){n=g.q(n.streamsProgress);for(var p=n.next();!p.done;p=n.next())p.value.streamState=c}return h5(k,l.filter(function(r){return!!r}),"offlineVideoStreams")}):g.Ut.resolve(void 0)}),4);
if(2!=f.j)return g.va(f,0);e=g.wa(f);return e instanceof g.Nt&&"QUOTA_EXCEEDED"===e.type?g.w(f,a.Oq("TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"),0):f.eb(0)})},FZa=function(a,b){var c;
return g.A(function(d){if(!a.j)return d.return();c=a.j;return g.w(d,l5(a.u,{mode:"readwrite",Kc:!0},function(e){var f=[g5(e,c,"transfer")];b&&f.push(b(e));return g.Ut.all(f)}),0)})},$5=function(a){a.j=void 0;
a.B=void 0;a.C.stop()},yZa=function(a,b){var c,d,e,f;
return g.A(function(k){if(1==k.j)return c=g.VK(b.key),d=c.entityId,e=g.WK(d,"playbackData"),g.w(k,o5(a.u,e,"playbackData"),2);f=k.u;if(null===f||void 0===f?0:f.playerResponseJson)return k.return(JSON.parse(f.playerResponseJson));throw Error("No PlayerResponse found");})},c6=function(a){a.C.start(a.Ea||6E4)},zZa=function(a){return void 0!==e6[a.transferState]},AZa=function(a,b){var c=e6[a.transferState],d=e6[b.transferState];
return c!==d?c-d:Number(a.enqueuedTimestampMs)-Number(b.enqueuedTimestampMs)},f6=function(a,b){var c=this;
this.Y=a;this.api=b;this.N=new g.Tu;this.u=new aZa(function(){return GZa(c)},function(){HZa(c)},this.api.Ao(),this.api.S.bind(this.api));
this.B=new U5(this.api);this.C=new g.ek;bZa(this.u)},GZa=function(a){return g.A(function(b){a.api.Qa("onOrchestrationBecameLeader");
a.j&&a.D||IZa(a).then(a.C.resolve).catch(a.C.reject);var c=a.C.promise;return g.w(b,c,0)})},IZa=function(a){var b,c,d;
return g.A(function(e){if(1==e.j)return g.w(e,r5(),2);if(3!=e.j){b=e.u;if(!b)return I5("PES is undefined"),e.return();a.j=new Z5(b,a.api,a.u,a.B);c=a.hF(b);d=a;return g.w(e,MYa(b,c,a.u,a.B),3)}d.D=e.u;return g.w(e,JZa(a),0)})},JZa=function(a){var b;
return g.A(function(c){switch(c.j){case 1:if(!a.j)return I5("transferManager is undefined"),c.return();if(!a.api.S("woffle_orch_init_killswitch")&&a.j.j){c.eb(2);break}return g.w(c,a6(a.j),2);case 2:return g.w(c,a.Px(),4);case 4:return a.J=g.Jr(function(){a.Px()},9E5),g.as(g.cs(),function(){a.j&&tZa(a.j)}),g.w(c,r5(),5);
case 5:return b=c.u,g.w(c,XYa(b),6);case 6:cZa(a.u),g.ta(c)}})},HZa=function(a){var b,c;
g.A(function(d){if(1==d.j)return a.j||a.D?g.w(d,a.C.promise,2):d.return();void 0!==a.J&&(g.Lr(a.J),a.J=void 0);null===(b=a.j)||void 0===b?void 0:b.dispose();a.j=void 0;null===(c=a.D)||void 0===c?void 0:c.dispose();a.D=void 0;a.api.Qa("onOrchestrationLostLeader");a.C=new g.ek;g.ta(d)})},KZa=function(){var a,b,c,d,e,f;
return g.A(function(k){switch(k.j){case 1:return g.w(k,r5(),2);case 2:a=k.u;if(!a)return k.return([]);b=Date.now()/1E3;return g.w(k,p5(a,"offlineVideoPolicy"),3);case 3:c=k.u,d=g.q(c),e=d.next();case 4:if(e.done){k.eb(6);break}f=e.value;if(!(f.expirationTimestamp&&Number(f.expirationTimestamp)<b)){k.eb(5);break}f.action="OFFLINE_VIDEO_POLICY_ACTION_DISABLE";return g.w(k,n5(a,f,"offlineVideoPolicy"),5);case 5:e=d.next();k.eb(4);break;case 6:return k.return(c.map(function(l){return l.key}))}})},g6=
function(a,b,c,d,e){var f,k,l;
return g.A(function(m){if(1==m.j)return g.w(m,r5(),2);f=m.u;if(!f)return m.return([]);k=b.map(function(n){var p=g.WK(n,c);p={actionType:d,entityKey:p,actionMetadata:Object.assign(Object.assign({},CYa()),e)};"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"!==d&&(p.actionMetadata.priority=0);n=new M5(c,n,p);return N5(n)});
l=aYa(f,k);bZa(a.u);return m.return(l)})},MZa=function(a){var b,c,d,e;
return g.A(function(f){if(1==f.j)return b=g.rK(),c=EXa(a),d=g.VJ(LZa),g.w(f,g.aI(b,c,d),2);e=f.u;if(!e)throw Error("Network request failed");if(!e.videos||!e.videos.length)throw Error("No data");return f.return(e.videos.map(function(k){return k.offlineVideoData}))})},h6=function(a,b,c){this.j=a;
this.Y=b;this.u=c},PZa=function(a,b){var c,d,e,f,k,l;
return g.A(function(m){switch(m.j){case 1:return c=A5(b),d=g.VK(b.entityKey),e=d.entityId,g.ua(m,2),g.w(m,NZa(a,e),4);case 4:g.va(m,3);break;case 2:return f=g.wa(m),k="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.Nt&&"QUOTA_EXCEEDED"===f.type&&(k="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,k));case 3:var n;var p=null!==(n=b.actionMetadata)&&void 0!==n&&n.ytMainDownloadedVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.ytMainDownloadedVideoEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=OZa("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},QZa=function(a,b){var c,d,e,f,k,l,m;
return g.A(function(n){switch(n.j){case 1:return c=A5(b),d=g.VK(b.entityKey),e=d.entityId,g.w(n,o5(a.j,b.entityKey,"ytMainDownloadedVideoEntity"),2);case 2:f=n.u;if(!f)return n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(n,3);return g.w(n,NZa(a,e,f.addedTimestampMillis),5);case 5:k=OZa("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.va(n,4);break;case 3:return l=g.wa(n),l instanceof Error&&"No data"===l.message?g.w(n,F5(e,a.j,b,a.u),4):(m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",
l instanceof g.Nt&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m)));case 4:return n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,k?[k]:void 0))}})},RZa=function(a,b){var c,d;
return g.A(function(e){switch(e.j){case 1:return c=A5(b),g.ua(e,2),d=g.VK(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.w(e,rYa(a.j,b,a.u),5):g.w(e,F5(d,a.j,b,a.u),5);case 5:g.va(e,3);break;case 2:return g.wa(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},NZa=function(a,b,c){var d,e,f,k,l,m;
return g.A(function(n){switch(n.j){case 1:return g.w(n,MZa([b]),2);case 2:return d=n.u,e=d[0],g.w(n,SZa(a,e,c),3);case 3:f=n.u;k=f.videoEntity;l=f.channelEntity;g.ua(n,4);var p=D5(k.thumbnail),r=D5(l.avatar);return g.w(n,kYa(p.concat(r)),6);case 6:g.va(n,0);break;case 4:m=g.wa(n);if(!a.Y.S("woffle_disable_thumbnails"))throw m;g.ta(n)}})},SZa=function(a,b,c){var d,e,f,k,l;
return g.A(function(m){if(1==m.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null===(d=b.channel)||void 0===d?void 0:d.offlineChannelData;f={id:g.WK(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};k={id:g.WK(b.videoId,"ytMainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?
Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,channelOwner:f.id};l={id:g.WK(b.videoId,"ytMainDownloadedVideoEntity"),video:k.id,playbackData:g.WK(b.videoId,"playbackData"),offlineVideoPolicy:g.WK(b.videoId,"offlineVideoPolicy"),addedTimestampMillis:c};return g.w(m,l5(a.j,{mode:"readwrite",Kc:!0},function(n){var p=g5(n,f,"ytMainChannelEntity"),r=g5(n,k,"ytMainVideoEntity");n=g5(n,
l,"ytMainDownloadedVideoEntity");return g.Ut.all([p,r,n])}),2)}return m.return({videoEntity:k,
channelEntity:f,Fga:l})})},OZa=function(a,b,c){b=g.WK(b,"playbackData");
c=Object.assign(Object.assign({},c),{priority:1,retryScheduleIntervalsInSeconds:TZa});return{actionType:a,entityKey:b,actionMetadata:c}},i6=function(){f6.apply(this,arguments);
this.K="ytMainDownloadedVideoEntity"},j6=function(){g.BL.apply(this,arguments)};
g.v(y4,x4);g.v(z4,y4);z4.prototype.Wd=function(){return[]};
g.v(A4,y4);A4.prototype.Wd=function(){var a=[];this.j.alternateChannel&&a.push(this.j.alternateChannel);this.j.alternateChannelList&&a.push.apply(a,g.la(this.j.alternateChannelList));this.j.oneofChannelEntity&&a.push(this.j.oneofChannelEntity);return[].concat(g.la(new Set(a)))};
g.v(B4,y4);B4.prototype.Wd=function(){var a=[];this.j.entryCollection&&a.push(this.j.entryCollection);return[].concat(g.la(new Set(a)))};
g.v(C4,x4);C4.prototype.Wd=function(){var a=[];this.j.video&&a.push(this.j.video);return[].concat(g.la(new Set(a)))};
g.v(D4,y4);D4.prototype.Wd=function(){var a=[];this.j.parentPlaylist&&a.push(this.j.parentPlaylist);if(this.j.entries)for(var b=g.q(this.j.entries),c=b.next();!c.done;c=b.next())a.push.apply(a,g.la((new C4(c.value)).Wd()));return[].concat(g.la(new Set(a)))};
g.v(E4,y4);E4.prototype.Wd=function(){var a=[];this.j.descriptionEntity&&a.push(this.j.descriptionEntity);this.j.creators&&a.push.apply(a,g.la(this.j.creators));this.j.theBiggestFan&&a.push(this.j.theBiggestFan);return[].concat(g.la(new Set(a)))};
g.v(F4,y4);F4.prototype.Wd=function(){return[]};
g.v(G4,y4);G4.prototype.Wd=function(){return[]};
g.v(H4,y4);H4.prototype.Wd=function(){return[]};
g.v(I4,y4);I4.prototype.Wd=function(){return[]};
g.v(J4,y4);J4.prototype.Wd=function(){return[]};
g.v(K4,y4);K4.prototype.Wd=function(){var a=[];this.j.fakeChildren&&a.push.apply(a,g.la(this.j.fakeChildren));return[].concat(g.la(new Set(a)))};
g.v(L4,y4);L4.prototype.Wd=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playbackData&&a.push(this.j.playbackData);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.la(new Set(a)))};
g.v(M4,y4);M4.prototype.Wd=function(){return[]};
g.v(N4,y4);N4.prototype.Wd=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.playbackPosition&&a.push(this.j.playbackPosition);this.j.downloadStatus&&a.push(this.j.downloadStatus);return[].concat(g.la(new Set(a)))};
g.v(O4,y4);O4.prototype.Wd=function(){return[]};
g.v(P4,y4);P4.prototype.Wd=function(){return[]};
g.v(Q4,y4);Q4.prototype.Wd=function(){return[]};
g.v(R4,y4);R4.prototype.Wd=function(){return[]};
g.v(S4,y4);S4.prototype.Wd=function(){return[]};
g.v(T4,y4);T4.prototype.Wd=function(){return[]};
g.v(U4,y4);U4.prototype.Wd=function(){var a=[];this.j.transfer&&a.push(this.j.transfer);this.j.adsPlaybackData&&a.push.apply(a,g.la(this.j.adsPlaybackData));this.j.drmLicense&&a.push(this.j.drmLicense);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.la(new Set(a)))};
g.v(V4,y4);V4.prototype.Wd=function(){var a=[];this.j.offlineVideoStreams&&a.push.apply(a,g.la(this.j.offlineVideoStreams));this.j.captionTrack&&a.push.apply(a,g.la(this.j.captionTrack));return[].concat(g.la(new Set(a)))};
g.v(W4,y4);W4.prototype.Wd=function(){return[]};
var LZa=["offline"],xYa=["offline/get_playback_data_entity"],UZa={m1:"captionTrack",H8:"ytMainChannelEntity",I8:"ytMainDownloadedVideoEntity",J8:"ytMainVideoEntity",Aaa:"offlineOrchestrationActionWrapperEntity",Kaa:"offlineVideoPolicy",Laa:"offlineVideoStreams",zba:"playbackData",aea:"transfer",uca:"orchestrationWebSamplingEntity"};g.v(Y4,g.Xs);g.v($4,JXa);$4.prototype.B=function(a,b){b=Z4(b);a=(new TextEncoder).encode(JSON.stringify(a));return this.j.encrypt(a,b)};
$4.prototype.u=function(a,b){if(!(a instanceof Uint8Array))throw FXa(1);var c=new TextDecoder;b=Z4(b);a=this.j.decrypt(a,b);return JSON.parse(c.decode(a))};
g.v(a5,JXa);a5.prototype.B=function(a){return a};
a5.prototype.u=function(a){if(a instanceof Uint8Array)throw FXa(0);return a};
var NXa={captionTrack:Q4,channelHandle:z4,commerceCartListEntity:W4,downloadQualityPickerEntity:I4,fakeChannel:A4,fakePlaylist:B4,fakePlaylistEntryCollection:D4,fakeVideo:E4,fakeVideoDescription:F4,liveChatPollStateEntity:H4,logoEntity:G4,markersVisibilityOverrideEntity:O4,offlineOrchestrationActionWrapperEntity:R4,offlineVideoPolicy:S4,offlineVideoStreams:T4,offlineabilityEntity:J4,orchestrationWebSamplingEntity:K4,pinnedProductEntity:P4,playbackData:U4,transfer:V4,ytMainChannelEntity:M4,ytMainDownloadedVideoEntity:L4,
ytMainVideoEntity:N4},c5;g.v(k5,g.G);k5.prototype.B=function(a){$Xa(this,a.data)};
k5.prototype.ra=function(){this.channel.close()};
var q5;var w5=g.B.caches,v5,x5;s5.prototype.open=function(a){return w5.open(u5(a))};
s5.prototype.has=function(a){return w5.has(u5(a))};
s5.prototype.delete=function(a){return w5.delete(u5(a))};
s5.prototype.match=function(a,b){var c=this,d,e,f,k,l,m;return g.A(function(n){switch(n.j){case 1:return g.w(n,c.keys(),2);case 2:d=n.u,e=g.q(d),f=e.next();case 3:if(f.done){n.eb(5);break}k=f.value;return g.w(n,c.open(k),6);case 6:return l=n.u,g.w(n,l.match(a,b),7);case 7:if(m=n.u)return n.return(m);f=e.next();n.eb(3);break;case 5:return n.return()}})};
g.v(t5,s5);t5.prototype.keys=function(){var a,b,c,d,e,f,k,l,m;return g.A(function(n){if(1==n.j)return a=[],b=g.Jt("CacheStorage keys"),g.w(n,w5.keys(),2);c=n.u;d=g.q(c);for(e=d.next();!e.done;e=d.next()){f=e.value;var p=f.indexOf(":");k=-1===p?{vB:f}:{vB:f.substring(0,p),datasyncId:f.substring(p+1)};l=k.vB;m=k.datasyncId;m===b&&a.push(l)}return n.return(a)})};Object.keys(UZa).map(function(a){return UZa[a]});
var qYa="captionTrack ytMainChannelEntity ytMainDownloadedVideoEntity ytMainVideoEntity offlineVideoPolicy offlineVideoStreams playbackData transfer".split(" ");g.v(J5,G5);J5.prototype.B=function(a){return B5(a)?vYa(this,a):C5(a)?wYa(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.v(L5,G5);L5.prototype.B=function(a){return B5(a)?zYa(this,a):C5(a)?AYa(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_UPDATE"===a.actionType&&a.entityKey?this.handleUpdate(a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
L5.prototype.handleUpdate=function(a){var b=this,c,d,e;return g.A(function(f){switch(f.j){case 1:return c=A5(a),g.w(f,o5(b.j,a.entityKey,"transfer"),2);case 2:d=f.u;if(!d||"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"!==d.transferState)return f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(f,3);d.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE";return g.w(f,n5(b.j,d,"transfer"),5);case 5:e=g.VK(d.key).entityId;z5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_PLAYER_RESPONSE_REFRESH",
statusType:"ADDED_TO_QUEUE"},{videoId:e,lj:d});g.va(f,4);break;case 3:return g.wa(f),f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})};var RYa=["OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD","OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"];var O5;IYa.prototype.j=function(a,b){var c=a.action.actionMetadata.priority-b.action.actionMetadata.priority;0===c&&(a.j<b.j?c=-1:a.j>b.j&&(c=1));return c};g.v(R5,g.G);R5.prototype.ra=function(){this.K&&this.K();g.G.prototype.ra.call(this)};
R5.prototype.createAction=function(a,b){var c=g.VK(a.entityKey).entityType,d=g.Jv(16);return new M5(c,d,a,b.actionId,b.rootActionId)};
R5.prototype.Z=function(a){var b=this,c,d,e,f,k,l,m,n,p;return g.A(function(r){if(1==r.j){if(b.isDisposed())return r.return();d=null!==(c=a.offlineOrchestrationActionWrapperEntity)&&void 0!==c?c:new Set;e=[];f=g.q(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.VK(l),n=m.entityId,KYa(b.j,n)||e.push(l);return g.w(r,TYa(b,e),2)}p=r.u;return g.w(r,T5(b,p),0)})};
R5.prototype.retry=function(){var a=this;return g.A(function(b){return g.w(b,UYa(a),0)})};g.v(U5,g.G);U5.prototype.B=function(a){this.api.Qa("onOfflineOperationFailure",a.data)};
U5.prototype.C=function(a){this.api.ea("offlinetransferpause",a.data)};
U5.prototype.ra=function(){var a,b;null===(a=this.j)||void 0===a?void 0:a.close();null===(b=this.u)||void 0===b?void 0:b.close()};YYa.prototype.request=function(a,b,c){b=void 0===b?{}:b;return this.locks.request(a,b,function(d){return c(d)})};aZa.prototype.Oe=function(){this.j&&V5(this)};g.h=iZa.prototype;
g.h.VW=function(a){var b=this,c,d,e;return g.A(function(f){if(!g.T(a.state,128))return f.eb(0);var k=null===(c=a.state.getData())||void 0===c?void 0:c.errorCode,l=null===(d=a.state.getData())||void 0===d?void 0:d.rH;e="net.retryexhausted"===k&&(null===l||void 0===l?0:l.includes("net.connect"))?"TRANSFER_FAILURE_REASON_NETWORK_LOST":(null===k||void 0===k?0:k.startsWith("net."))?"TRANSFER_FAILURE_REASON_NETWORK":"TRANSFER_FAILURE_REASON_INTERNAL";return g.w(f,b.Oq(b.player.getVideoData().videoId,e),
0)})};
g.h.Oq=function(a,b){var c=this;return g.A(function(d){if(1==d.j){if(c.u)return d.return();c.u=!0;return"TRANSFER_FAILURE_REASON_NETWORK_LOST"===b?(X5(c,a,!1,!0),d.eb(0)):g.w(d,W5(c,a),3)}g.FD(a,4);return g.w(d,c.j.Oq(b),0)})};
g.h.lB=function(a){2===a.status?(a.status!==this.B&&(b6(this.j),g.FD(a.videoId,2)),a.Ix&&CZa(this.j,a.videoId,a.Ix)):4===a.status?(W5(this,a.videoId),this.Oq(a.videoId,a.zA?"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":"TRANSFER_FAILURE_REASON_INTERNAL")):1===a.status&&BZa(this.j);this.B=a.status;this.api.Qa("localmediachange",{videoId:a.videoId,status:a.status})};
g.h.OG=function(){var a=this,b;return g.A(function(c){if(1==c.j){if(a.u)return c.return();a.u=!0;b=a.player.getVideoData().videoId;return g.w(c,W5(a,b),2)}return g.w(c,a.j.OG(),0)})};
g.h.S=function(a){return this.api.U().S(a)};g.v(Y5,g.G);Y5.prototype.ra=function(){this.u&&this.u();g.G.prototype.ra.call(this)};
Y5.prototype.B=function(a){var b=this,c,d,e,f,k,l,m,n;return g.A(function(p){d=null!==(c=a.transfer)&&void 0!==c?c:new Set;e=[];f=g.q(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.VK(l),n=m.entityId,e.push(n);return 0===e.length?p.return():g.w(p,pZa(b,e),0)})};g.v(Z5,g.G);g.h=Z5.prototype;g.h.ra=function(){this.K&&this.K();this.N.dispose();this.C.dispose();this.ma&&g.gg(this.D.B,this.ma);this.Z&&g.gg(this.D.B,this.Z);g.G.prototype.ra.call(this)};
g.h.gZ=function(a){var b=this,c,d;return g.A(function(e){if(1==e.j)return c=g.WK(a,"transfer"),b.j&&c===b.j.key?(X5(b.J,b.B,!0),b.C.stop(),e.eb(0)):g.w(e,l5(b.u,{mode:"readwrite",Kc:!0},function(f){return d5(f,c,"transfer").then(function(k){if(k&&"TRANSFER_STATE_COMPLETE"!==k.transferState&&"TRANSFER_STATE_FAILED"!==k.transferState)return k.transferState="TRANSFER_STATE_PAUSED_BY_USER",g5(f,k,"transfer").then(function(){return k})})}),3);
(d=e.u)&&lYa({videoId:a,lj:d});g.ta(e)})};
g.h.fZ=function(){this.j&&this.B&&X5(this.J,this.B,!1);this.C.stop()};
g.h.Ux=function(){this.j?vZa(this,this.j):a6(this)};
g.h.AS=function(a){var b=this,c;return g.A(function(d){switch(d.j){case 1:if(!b.j){d.eb(2);break}if("TRANSFER_STATE_COMPLETE"===b.j.transferState||"TRANSFER_STATE_FAILED"===b.j.transferState||!a.transfer||!a.transfer.has(b.j.key)){d.eb(3);break}c=b;return g.w(d,o5(b.u,b.j.key,"transfer"),4);case 4:c.j=d.u;if(b.j){d.eb(3);break}return g.w(d,wZa(b),3);case 3:if(b.j)return d.return();case 2:return g.w(d,a6(b),0)}})};
g.h.Oq=function(a,b){var c=this,d,e;return g.A(function(f){if(1==f.j){a:switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_PLAYABILITY":case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":var k=!1;break a;default:k=!0}return k&&DZa(c)?g.w(f,d6(c,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),5):g.w(f,EZa(c,a),3)}3!=f.j&&(d=g.VK(c.j.key).entityId,z5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_RETRY",statusType:"ADDED_TO_QUEUE"},
{videoId:d,lj:c.j}));$5(c);e=a6(c,!0);b&&b(e);g.ta(f)})};
g.h.OG=function(a){var b=this,c,d,e,f,k,l;return g.A(function(m){if(1==m.j)return DZa(b)?g.w(m,d6(b,"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"),5):g.w(m,EZa(b,"TRANSFER_FAILURE_REASON_STREAM_MISSING"),3);if(3!=m.j)return c=g.VK(b.j.key).entityId,z5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_PLAYER_RESPONSE_EXPIRATION",statusType:"ADDED_TO_QUEUE"},{videoId:c,lj:b.j}),d=CYa(),d.playbackDataActionMetadata={isEnqueuedForExpiredStreamUrlRefetch:!0},e=g.WK(c,"playbackData"),f={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",
entityKey:e,actionMetadata:d},k=N5(new M5("playbackData",c,f)),g.w(m,n5(b.u,k,"offlineOrchestrationActionWrapperEntity"),3);$5(b);l=a6(b,!0);a&&a(l);g.ta(m)})};
var k6={},e6=(k6.TRANSFER_STATE_TRANSFERRING=1,k6.TRANSFER_STATE_TRANSFER_IN_QUEUE=2,k6);g.h=f6.prototype;g.h.hF=function(a){var b={};return b.playbackData=new J5(a,this.Y,this.B),b.transfer=new L5(a),b};
g.h.isOrchestrationLeader=function(){return this.u.j};
g.h.fH=function(a){var b=this.B,c;b.api.ea("offlinetransferpause",a);null===(c=b.u)||void 0===c?void 0:c.postMessage(a)};
g.h.Ux=function(a){var b,c;return g.A(function(d){if(1==d.j)return g.w(d,r5(),2);b=d.u;if(!b)return d.return();c=g.WK(a,"transfer");return g.w(d,l5(b,{mode:"readwrite",Kc:!0},function(e){return d5(e,c,"transfer").then(function(f){return f&&"TRANSFER_STATE_PAUSED_BY_USER"===f.transferState?(f.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE",g5(e,f,"transfer").then(function(){z5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_USER_RESUME",statusType:"USER_RESUMED"},{videoId:a,lj:f});return g.Ut.resolve(null)})):
g.Ut.resolve(null)})}),0)})};
g.h.Px=function(a){a=void 0===a?43200:a;var b=this,c,d,e,f,k,l,m,n;return g.A(function(p){if(1==p.j)return b.N.Ne()?g.w(p,r5(),2):p.return(KZa());if(3!=p.j){c=p.u;if(!c)return p.return([]);d=Date.now()/1E3;return g.w(p,p5(c,"offlineVideoPolicy"),3)}e=p.u;f=[];k=g.q(e);for(l=k.next();!l.done;l=k.next())m=l.value,Number(m.lastUpdatedTimestampSeconds)+a<=d&&(n=g.VK(m.key).entityId,f.push(n));return f.length?p.return(g6(b,f,b.K,"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH")):p.return([])})};
g.h.deleteAll=function(){return g6(this,["!*$_ALL_ENTITIES_!*$"],this.K,"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE")};g.v(h6,G5);h6.prototype.B=function(a){return B5(a)?PZa(this,a):C5(a)?QZa(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE"===a.actionType&&a.entityKey?RZa(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var TZa=[10];g.v(i6,f6);i6.prototype.hF=function(a){var b=f6.prototype.hF.call(this,a);b.ytMainDownloadedVideoEntity=new h6(a,this.Y,this.B);return b};g.v(j6,g.BL);g.h=j6.prototype;g.h.create=function(){var a=this.player.U();g.cD(a)&&(this.j=new i6(a,this.player))};
g.h.Zh=function(){return!1};
g.h.sH=function(a,b,c,d){var e=this;return g.A(function(f){return e.j?f.return(g6(e.j,a,b,c,d)):f.return(Promise.reject())})};
g.h.deleteAll=function(){return this.j.deleteAll()};
g.h.Px=function(a){return this.j.Px(a)};
g.h.fH=function(a){this.j.fH(a)};
g.h.Ux=function(a){return this.j.Ux(a)};
g.h.isOrchestrationLeader=function(){return this.j.isOrchestrationLeader()};g.AL("offline",j6);})(_yt_player);
